### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by d4h0** [bloodyowl/rescript-pages#2]
Hi,

This looks great – thanks for creating ReScript Pages!

Is there a roadmap?

At the moment, ReScript Pages seems to be pretty opinionated regarding how to do things. Is a plugin system similar to Gatsby planned?

For example, currently (with Gatsby) I'm using `mdx` pages instead of Markdown.

**Comment by bloodyowl** [comment]
Hi!

Right now there's no official roadmap, although I can assure there will be no plug-in system 😄

Things I'm investigating right now:
- providing sources in a more flexible way (like providing a function that fetches content and gives them in a strict format)
- transforming markdown body to a tree (so that at runtime you can manage it with whatever react component you like)

The rest won't likely change for a while.

**Comment by d4h0** [comment]
> Right now there's no official roadmap, although I can assure there will be no plug-in system

Alright, thanks for letting me know! I'll keep an eye on the project.
